Dealing with change in arb directory case

diff --git a/bin/arb b/bin/arb
--- a/bin/arb
+++ b/bin/arb
@@ -362,7 +362,7 @@ if [ -n "$previous_build_dir" ] ; then
   if [ ! -d "$previous_build_dir" ] ; then
     echo "WARNING: previous build directory $previous_build_dir does not exist.  Not using previous build data.";
   else
-    cp -p "$previous_build_dir/"* "$build_dir/" >/dev/null 2>/dev/null ;
+    cp -p "$previous_build_dir/"* "$build_dir/" >/dev/null 2>/dev/null ; # preserve properties but don't copy directories (ie, intel ooc dir)
   fi;
 fi;
 # and link to the makefile
@@ -385,14 +385,15 @@ if [ -z "$previous_output_dir" ] ; then # -z is true if the string is empty/does
   if [ ! -d "$previous_run" ] ; then mkdir -p "$previous_run" ; fi ;
   rm "$previous_run/"* >/dev/null 2>/dev/null ;
 # place old output and gmsh files in previous_run directory that are needed to restart the run
-  ( cd "$output_dir"; # open subshell to limit cd scope
-  for i in ${output_files_to_keep[@]} ; do # don't quote string here as want globs to expand
-    if [ $ocontinue -eq 0 ] ; then
-      mv "$i" "$previous_run/" >/dev/null 2>/dev/null ;
-    else
-      cp -pR "$i" "$previous_run/" >/dev/null 2>/dev/null ;
-    fi ;
-  done ;
+  (
+    cd "$output_dir"; # open subshell to limit cd scope (on newline due to vim highlighting error)
+    for i in ${output_files_to_keep[@]} ; do # don't quote string here as want globs to expand
+      if [ $ocontinue -eq 0 ] ; then
+        mv "$i" "$previous_run/" >/dev/null 2>/dev/null ;
+      else
+        cp -pR "$i" "$previous_run/" >/dev/null 2>/dev/null ;
+      fi ;
+    done ;
   )
 else # have to deal with previous_output_dir
   if [ $ocontinue -eq 1 ] ; then
@@ -552,12 +553,28 @@ if [ $ocompile -eq 1 -o $osetup -eq 1 ] ; then
       fi ;
     fi
 
+# check to see whether src directory is the same as last time too, and if not, we'll have to clean setup too
+    if [ -e last_src_dir ] ; then
+      last_src_dir=`cat last_src_dir`;
+      if [ ! "$src_dir" = "$last_src_dir" ] ; then
+        echo "INFO: cleaning of compilation files required as src directory has changed since the last run:";
+        echo "      src_dir = $src_dir"
+        echo "      last_src_dir = $last_src_dir"
+        make compiler=$compiler clean_setup;
+        if [ "$?" -ne 0 ] ; then
+          echo "ERROR: problem cleaning setup files from the build directory due to a different src directory being used" ;
+          cd "$working_dir"; exit 1 ;
+        fi ;
+      fi ;
+    fi
+
   # record options used this time
     touch last_compiler_was_$compiler ;
     touch last_compile_had_debugging_$odebug ;
     touch last_compile_had_omp_$oomp ;
     touch last_compile_had_opt_$oopt ;
     touch last_compile_had_ilp_$oilp ;
+    echo $src_dir >last_src_dir;
 
   fi
 
