mainly changes to test_suite script

diff --git a/misc/test_suite/test_suite b/misc/test_suite/test_suite
--- a/misc/test_suite/test_suite
+++ b/misc/test_suite/test_suite
@@ -38,6 +38,27 @@
 # daltonh, 24/11/10
 
 # usage: from the working directory run ./misc/test_suite/test_suite
+#-------------------------------------------------------------------------------
+# usage function
+usage () {
+  echo
+  echo "HELP/USAGE: ./misc/test_suite/testsuite [options] [test_case1] [test_case2] [etc]";
+  echo
+  echo "This script will run through all of the test problems within the examples directory";
+  echo "Run from the working directory (as above)";
+  echo "Alternatively, if any test_case's are specified, only they will be run";
+  echo
+  echo "Possible options:";
+  echo "  --clean|-c: remove previous results and run all tests";
+  echo "  --refresh|r: only run the tests that were previously unsuccessful (default)";
+  echo "  --help|-h: display this HELP INFO";
+  echo "  --compiler-gnu: use the gfortran compiler";
+  echo "  --compiler-intel: use the intel compiler";
+  echo "  --compiler-both: use both compilers sequentially (default)";
+  echo;
+  exit 1;
+}
+#-------------------------------------------------------------------------------
 cwd=`pwd`;
 examples_dir=$cwd'/examples';
 #examples_dir=$cwd'/examples_test';
@@ -46,9 +67,49 @@ log_file=$cwd'/test_suite.log'
 saved_dir=$cwd'/saved_input_files'
 stopfile='test_suite_stop'
 error=0;
-refresh=0; # if refresh is on, only runs that were unsuccessful on the last run are repeated
+REFRESH=1; # default is refresh is on
+COMPILER="both"; # both compilers used by default
+unset TESTCASES;
+
+# check for any options
+for i in $*
+do
+  case $i in
+    "--refresh"|"-r") REFRESH=1;; # only runs that were unsuccessful on the last run are repeated (default behaviour)
+    "--clean"|"-c") REFRESH=0;; # rerun all simulations whether or not they were successful or not previously
+    "--compiler-gnu") COMPILER="gnu";;
+    "--compiler-intel") COMPILER="intel";;
+    "--compiler-both") COMPILER="both";;
+    "--help"|"-h") usage;;
+    *) echo "INFO: adding test case $i"; TESTCASES[${#TESTCASES[@]}]=$i;;
+  esac
+done ;
 
 if [ -e $log_file ] ; then rm $log_file ; fi;
+
+# check that examples are in the right location
+if [ ! -d $examples_dir ] ; then
+  echo "ERROR: examples directory $examples_dir does not exist";
+  exit 1;
+fi;
+
+# if no test cases have been specifically given, set to all within the examples directory
+if [ -z "${TESTCASES[0]}" ] ; then
+  cd $examples_dir;
+  TESTCASES=( "*" );
+  cd ..;
+fi;
+echo "INFO: attempting to run within the following directories (validity checked later): $TESTCASES" >>$log_file;
+
+# set compilers based on COMPILER option
+unset COMPILERS;
+if [ $COMPILER = "both" ] ; then
+  COMPILERS[0]="gnu";
+  COMPILERS[1]="intel";
+else
+  COMPILERS[0]=$COMPILER;
+fi;
+echo "INFO: using the following compilers: $COMPILERS" >>$log_file;
 
 # check that suitesparse solver is in the right location
 if [ ! -d $suitesparse_dir ] ; then
@@ -72,12 +133,6 @@ else
   cd $cwd;
 fi ;
 
-# check that examples are in the right location
-if [ ! -d $examples_dir ] ; then
-  echo "ERROR: examples directory $examples_dir does not exist";
-  exit 1;
-fi;
-
 # create saved_dir and move input files into it for later replacement
 if [ -d $saved_dir ] ; then
   echo "ERROR: the saved input files directory $saved_dir already exists - delete or rename";
@@ -97,16 +152,23 @@ rm output/*warnings.txt >/dev/null 2>/dev/null;
 rm output/*details.txt  >/dev/null 2>/dev/null;
 
 # run through each example problem
-for subdir in $examples_dir/* ; do
+for dir_name in $TESTCASES ; do
+  subdir=$examples_dir/$dir_name;
+  if [ ! -d $subdir ] ; then
+    echo "INFO: skipping directory $subdir as it does not exist";
+    echo "INFO: skipping directory $subdir as it does not exist" >>$log_file;
+    continue;
+  fi
   if [ ! -f $subdir/*.arb -o -L $subdir ] ; then
     echo "INFO: skipping directory $subdir as it is a link to another directory or does not contain an arb input file";
+    echo "INFO: skipping directory $subdir as it is a link to another directory or does not contain an arb input file" >>$log_file;
     continue;
   fi # skip the directory if it doesn't contain an arb input file or is not a directory (could be a tutorial link for example)
-  for compiler in "gnu" "intel" ; do # run with both compilers
+  for compiler in $COMPILERS ; do # run with the chosen compilers
 # make results directory within examples directories and copy over all of the outputs
     results_dir=$subdir/resources/test_suite_results/$compiler;
     if [ ! -d $results_dir ] ; then mkdir -p $results_dir ; fi
-    if [ $refresh -eq 1 -a -e $results_dir/SUCCESS ] ; then
+    if [ $REFRESH -eq 1 -a -e $results_dir/SUCCESS ] ; then
       echo "INFO: skipping arb simulation of test case $subdir using $compiler compiler as successful results already exist";
       echo "INFO: skipping arb simulation of test case $subdir using $compiler compiler as successful results already exist" >>$log_file;
       continue;
